### ISSUE TITLE
Questions about GPU requirements

### ISSUE THREAD

**Issue by deyang2000** [NguyenVanVuong613/Finetune_SAM2#1]
Hi, there.
I'm looking into fine-tuning methods for SAM2. My current training conditions are 2*3090 (24G) and 8*A100 (40G). May I ask the author in what environment did you train? Do I need to buy an upgrade package on Colab to use the A100?

**Comment by NguyenVanVuong613** [comment]
> Hi, there. I'm looking into fine-tuning methods for SAM2. My current training conditions are 2_3090 (24G) and 8_A100 (40G). May I ask the author in what environment did you train? Do I need to buy an upgrade package on Colab to use the A100?

Hi there, sorry for the late reply.
This repository is just a test that I followed based on the following article: [Train and Fine-Tune Segment Anything 2 (SAM) in 60 Lines of Code](https://towardsdatascience.com/train-fine-tune-segment-anything-2-sam-2-in-60-lines-of-code-928dd29a63b3). In my case, I’m using a T4 GPU and it’s running fine, so I don’t think you need to buy an upgrade package on Colab.
